export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SELECT_ABSENT_EMPLOYEES = 'SELECT_ABSENT_EMPLOYEES';
export const DESELECT_ABSENT_EMPLOYEES = 'DESELECT_ABSENT_EMPLOYEES';
export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
